### ISSUE TITLE
Suggestion: Spy can appear as any traitor and Announcement to Traitors there is a spy

### ISSUE THREAD

**Issue by ToFurkie** [TTT-2/ttt2-role_spy#12]
Just a quality of life suggestion for the spy on both ends. Since spies can only appear as a normal traitor, if a vampire or hitman spawns, it’s easy for another traitor to figure out who is the spy in the game. If it was set up so a spy can appear as any traitor role, it gives the spy more capabilities to sow the seeds of doubt. Of course, spies appearing as vampires won’t appear in bloodlust and they can’t be changed to a grave robber

With a spy buff listed above, there should be a notification either in the middle of the screen or in chat saying there is a spy. This could be a convar setting to enable/disable this notification

**Comment by TimGoll** [comment]
There already is a convar for something like that

ttt2_spy_jam_special_roles

However it should be enabled by default

**Comment by ToFurkie** [comment]
Is that what that does? My group assumed that was chat/voice chat jamming. So how does the convar work? Does it make it so that no special traitors can spawn or does it allow spies to show up as any traitor?

It’d be nice to include this is included in the Spy steam page. I just assumed it was for the chat

**Comment by TimGoll** [comment]
It shows every traitor role as a normal traitor. E.g. a vampire is shown as a normal traitor as well

The settings will be reworked in a future update which will greatly improve to figure out what they mean

**Comment by ToFurkie** [comment]
Okay, sweet. Thanks for the clarification! I’ll go ahead and close this one then
