### ISSUE TITLE
Spy enables other roles to see the traitors and spy radar point is marked red for everyone

### ISSUE THREAD

**Issue by NotDaniel59** [TTT-2/ttt2-role_spy#29]
v0.9.2b

Issue:
Every role that is not in the innocent layer and detective, besides the unknown, so all other roles which are not in "no team", is able to see the traitors when a spy is in the game and the radar point of the spy is marked red for every role even innocents.

Collection:
https://steamcommunity.com/workshop/filedetails/?id=2466441155

Bot 19 is the spy in this case:
![hl2_2021-07-19_15-27-30](https://user-images.githubusercontent.com/28601384/126167325-55c7ad27-b890-48ba-b20a-1aa16f5823a0.jpg)

As Unknown:
![hl2_2021-07-19_15-30-10](https://user-images.githubusercontent.com/28601384/126167544-d52de80b-64c5-4409-b086-9606ffce14c3.jpg)

Radar sees spy:
![hl2_2021-07-19_15-33-19](https://user-images.githubusercontent.com/28601384/126167956-ea3d1a25-df10-4942-8d07-2320b4aa898b.jpg)

**Comment by TimGoll** [comment]
This was fixed in the latest update
