### ISSUE TITLE
Reborn you T

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_spy#4]
If you died a spy and you were revived with a defibrillator, then you become a traitor and can even buy items, the screenshot shows it.
![шпион](https://user-images.githubusercontent.com/7480655/60811977-e846a680-a1a9-11e9-8432-f6d74e2afc94.png)

**Comment by lebroomer** [comment]
Which defibrillator are you using?

**Comment by dok441** [comment]
https://pastebin.com/W9fzeC1Y

**Comment by lebroomer** [comment]
I wasn't able to reproduce the error, even with the same defibrillator. Does this bug occur every time or just sometimes?

**Comment by Histalek** [comment]
As there was no Answer to lebroomer's question for half a year i'm closing this issue.

Feel free to reopen if you can provide more information on the problem :)
