### ISSUE TITLE
Traitor voice chat not disabled when there is a spy

### ISSUE THREAD

**Issue by Jasorn** [TTT-2/ttt2-role_spy#5]
Was playing with friends and whenever there was a spy the traitors were able to just ask each other in T chat who is T, and the one that doesn't answer is obviously outted as the spy

**Comment by TimGoll** [comment]
Are you sure that you aren't using an old version?

**Comment by Alf21** [comment]
@TimGoll we should introduce a versioning for roles too ^^
@Jasorn Check TTT2 and the Spy for the newest version pls.

**Comment by TimGoll** [comment]
yes, indeed. For all addons really. ^^

**Comment by Alf21** [comment]
Maybe with an improved Changelog system

**Comment by TimGoll** [comment]
Yesterday when fixing bugs I thought the same thing! All our addons should be able to register them in the changelog system.

**Comment by Jasorn** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1683708655 this is the version i'm using, couldn't find any other one?

**Comment by TimGoll** [comment]
This is the right version. But sometimes steam caches old versions. You might want to delete the file from your server so it can be redownloaded. Additionally you have to clear your cache

**Comment by Jasorn** [comment]
alright, will give it a try

**Comment by Jasorn** [comment]
it disables text chat just fine but traitors are still able to talk in traitor voice chat

**Comment by Histalek** [comment]
As this was presumably fixed in 41fe02b757e626a515aa3cf358bddf7130a465f5 i'm closing this issue.

Feel free to reopen if the problem still persists :)

**Comment by Jasorn** [comment]
still didn't work, went into the code and changed in line 187 the hook, TTT2AvoidTeamVoiceChat -> TTT2CanUseVoiceChat, since i couldn't find any hook runs for avoid team voice chat. it now works

**Comment by Histalek** [comment]
Thank you for your report! The voice chat hooks were changed in ttt2 and the spy wasn't updated accordingly.

Should now be fixed :)
